version: '3'
services:
  # node-server:
  #   restart: always
  #   build: .
  #   ports:
  #     - 5000:5000
  #   links:
  #     - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: week13db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: root
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - 5050:80
  #   restart: always
  #   depends_on:
  #     - postgres
