version: '3'
services:
  node-server:
    restart: always
    build: .
    ports:
      - 5000:5000
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: week13db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
